version: '3.7'
services:
  whoami:
    image: containous/whoami
    networks:
      - caddy
    labels:
      caddy: img.bibica.net
      caddy.handle_path: /*
      caddy.handle_path.0_rewrite: * /bibica.net/wp-content/uploads/{uri}
      caddy.handle_path.1_reverse_proxy: {{https://i0.wp.com}}

networks:
  caddy:
    external: true
